version: "3"
services:
  postgres:
    image: postgres:9.4
    restart: always
    env_file: ./containerConfig/psql.env
    volumes:
      - ./containerConfig/initSql.sql:/docker-entrypoint-initdb.d/initSql.sql
      - ./data/psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
